name: Scheduled Playwright Tests

on:
  schedule:
    # Run on weekdays at 04:00 AM UTC
    - cron: "0 4 * * 1-5"
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  scheduled-e2e-tests:
    name: Scheduled Playwright Tests - ${{ matrix.environment }} - ${{ matrix.project }}
    strategy:
      fail-fast: false
      matrix:
        environment: [AT23, TT02]
        project: [e2e-tests]
    uses: ./.github/workflows/template-playwright.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      project: ${{ matrix.project }}
